name: WebSocket Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-websocket:
    runs-on: ubuntu-latest
    timeout-minutes: 4320  # 3 days
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
        
    - name: Build WebSocket Server
      run: npm run build:ws
        
    - name: Run WebSocket Server
      env:
        PORT: 8080
        NODE_ENV: production
      run: |
        echo "WebSocket server starting on port $PORT"
        node dist/websocket-server.js 