name: WebSocket Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-websocket:
    runs-on: ubuntu-latest
    timeout-minutes: 4320  # 3 days
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
        
    - name: Build WebSocket Server
      run: npm run build:ws
        
    - name: Run WebSocket Server
      env:
        PORT: 8080
      run: |
        echo "WebSocket server starting on port $PORT"
        npm run start:ws 